apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          ports:
            - containerPort: 80
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secret }}
                  key: mongodb-uri
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.name }}-session-secret
                  key: secret
            - name: PORT
              value: "9000"
            - name: LOG_LEVEL
              value: "info"
            - name: NODE_ENV
              value: "production"
            - name: VITE_CUSTOM_FAVICON_URL
              value: {{ .Values.app.theme_favicon_url }}
            - name: VITE_CUSTOM_LOGO_URL
              value: {{ .Values.app.theme_logo_url }}
            - name: VITE_CUSTOM_LOGO_ALT
              value: {{ .Values.app.theme_logo_alt_text }}
            - name: VITE_CUSTOM_NAVIGATION_COLOR
              value: {{ .Values.app.theme_color_navbar }}
            - name: VITE_CUSTOM_THEME_COLOR
              value: {{ .Values.app.theme_color_statusbar }}
            - name: VITE_CUSTOM_APP_NAME
              value: {{ .Values.app.theme_app_name }}
