app:
  name: unikalo-meow
  image: killiankopp/meow:1.17
  replicas: 1
  port: 3000
  url: meow.unikalo.koden.bzh
  namespace: koden-clients
  secret: unikalo-mongodb-secret
  theme_favicon_url: https://storage.googleapis.com/koden-public/unikalo/logo_preskription_256.png
  theme_logo_url: https://storage.googleapis.com/koden-public/unikalo/logo-vertical.png
  theme_logo_alt_text: Unikalo
  theme_color_navbar: "#1D1D1B"
  theme_color_statusbar: "#E3211F"
  theme_app_name: "Preskription"
